### ISSUE TITLE
Support async functions as handlers?

### ISSUE THREAD

**Issue by nwwells** [krasimir/stent#2]
Curious if this could be supported.

**Comment by krasimir** [comment]
Hey, seems interesting. What's on your mind? I mean how did you come with this need.

**Comment by nwwells** [comment]
Well, we a lot of Promise-based APIs (including `fetch`), which requires some boilerplate to fit into a generator-based API like you currently have in `stent`

**Comment by krasimir** [comment]
I see. I'll add it and will ping you here once it's done.

**Comment by nwwells** [comment]
I see now that you support functions that return promises in a `call`:

https://github.com/krasimir/stent#yield-callfunction-args

I think that may be the boilerplate I needed, actually. It may make more sense than directly using async functions as handlers anyway, because I think you want to `yeild` some state change before you start the async operation. I should get into this a bit more before you go ahead and add it.

**Comment by krasimir** [comment]
Yep, exactly. The generator as a handler is more flexible because you may `yield` a new state + handling such promise-like calls. Same as redux-saga project. Having the ability to do more then one thing in a single function. In the context of stent this is a state machine transition + async operation.

**Comment by nwwells** [comment]
Cool. I'll go with that then
