### ISSUE TITLE
Allow server side rendering

### ISSUE THREAD

**Issue by mateusvahl** [krasimir/stent#50]
The library is not doing server side rendering at moment,
Looks like we are avoiding render the component until it's connected, here:
https://github.com/krasimir/stent/blob/master/src/react/connect.js#L33

Please let me know if this is intentional and if we can just render the component immediately, before it's connected.

**Comment by illarionvk** [comment]
Enabling component render before it has connected to the machine breaks three tests:

![failing-tests-on-early-component-render](https://user-images.githubusercontent.com/5012724/90233044-cc3a1d80-de1d-11ea-9402-cdce06e47fbe.png)

**Comment by illarionvk** [comment]
Due to the nature of React hooks, we can never get the machine state on initial render, and [ReactDOMServer](https://reactjs.org/docs/react-dom-server.html) always renders an empty string.

However, we can fix server-side rendering if we connect to the machine in the Component class constructor and set the initial state before any rendering happens. Please take a look at my #51 pull-request.

**Comment by krasimir** [comment]
@illarionvk thank you for the PR. I like the changes.
@mateuspv there is a new version 8.0.4 released. Can you try and let us know how it goes.

**Comment by mateusvahl** [comment]
@krasimir @illarionvk thanks!
